# Generated by Django 4.2 on 2025-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uniq_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
